### ISSUE TITLE
unable to parse license - check protobufs

### ISSUE THREAD

**Issue by oop7** [CrymanChen/WKS-KEYS#11]
![Capture](https://github.com/CrymanChen/WKS-KEYS/assets/110548351/093c5a47-df7c-4557-afe2-0ed02edaaf06)

**Comment by CrymanChen** [comment]
Only a screenshot...

**Comment by oop7** [comment]
I am sorry, I am a beginner
Pssh:AAAAknBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAHISEMaSL659ol+gjFNCSDUlxRgSEMaSL659ol+gjFNCSDUlxRgSEMaSL659ol+gjFNCSDUlxRgSEMaSL659ol+gjFNCSDUlxRgSEMaSL659ol+gjFNCSDUlxRgSEMaSL659ol+gjFNCSDUlxRhI49yVmwY=
license url:https://license.inkryptvideos.com/api/v1/wj/license
![Capture0](https://github.com/CrymanChen/WKS-KEYS/assets/110548351/119f4662-b130-4966-9a1d-f89b1867a6f9)
![Capture1](https://github.com/CrymanChen/WKS-KEYS/assets/110548351/6d610ee0-f1e8-4a4b-82f4-6979e41e8788)
![Capture2](https://github.com/CrymanChen/WKS-KEYS/assets/110548351/13786997-885d-49ec-925e-3faa64fbc59f)
![Capture3](https://github.com/CrymanChen/WKS-KEYS/assets/110548351/fe9b7aac-4c77-4112-b8b8-6802863e40de)
[New folder.zip](https://github.com/CrymanChen/WKS-KEYS/files/13987665/New.folder.zip)
![Captur4](https://github.com/CrymanChen/WKS-KEYS/assets/110548351/ce062831-8391-48ef-a8b0-243bc9e1e8b2)
any anything else?

**Comment by CrymanChen** [comment]
You sent some sensitive information and data including your CDM, which may lead to your CDM being revoked. I suggest you emailing me these data again. As for if anything else, I wanna see the _Response_ of the license request.

**Comment by oop7** [comment]
ok i will send to your email and thank you
