### ISSUE TITLE
WKS-Keys  moduleNotFoundError

### ISSUE THREAD

**Issue by ghost** [CrymanChen/WKS-KEYS#14]
I'm having this error when running l3.py:

Traceback (most recent call last):

File "C:\Users\jrdss\Downloads\Tools\CDM\WKS-KEYS\l3.py", line 14, in <module>

from pywidevine.L3.cdm import cdm, deviceconfig

ModuleNotFoundError: No module named 'pywidevine.L3'

I have already placed the device_private_key and device_client_id_blob files in the L3\cdm\devices\android_generic folder

**Comment by CrymanChen** [comment]
Didn't see the pinned issue? #10
