### ISSUE TITLE
Can you review this again?

### ISSUE THREAD

**Issue by Fullna-ui** [CrymanChen/WKS-KEYS#16]
I want to start by apologizing for my earlier message. I wasn't aware that you were online, and I didn’t understand how the GitHub system worked. Based on your reaction, I assume you can see and receive all the posts I submit. I genuinely apologize for that. I intended to make a sincere and serious request for help. While it’s ideal to get assistance from you, the creator, if you closed my post due to my lack of knowledge, that would limit my opportunity to communicate and interact with others. I assure you that I meant no harm.

**Comment by Fullna-ui** [comment]
Of course, the message is a bit too personal, but it's still on topic. Can you please reconsider?

**Comment by Fullna-ui** [comment]
This time, I will write it in a formal tone and limit all unnecessary personal situations. Is that acceptable?

**Comment by Fullna-ui** [comment]
I want to clarify that spamming wasn't my intention. I was trying to adjust the format for better visibility for everyone. I assumed that it would take days to receive a response, so I didn't expect you to see the post almost simultaneously.

**Comment by Fullna-ui** [comment]
老兄我今天才注册的啊我怎么可能知道是什么情况你这判断下的也太仓促了吧，就算我反复发了同样的内容，但那些内容稍微看一眼就能确认不是骚扰用的废话啊

**Comment by Fullna-ui** [comment]
不是，我第一次就算无知是我的错你警告一下就可以了，这完全断绝沟通端口的处理也太不至于了吧，我好端端的为什么会平白无故的跑到这平台上恶意为之？我是真的在寻求帮助我发的那些内容难道还有其它解释吗？

**Comment by Fullna-ui** [comment]
而且重复的内容我都删掉了证明的确如我所说我只是在优化版型，唯一不妥当的就是你收到了很多提示消息，可这真的程度有那么严重吗？

**Comment by Fullna-ui** [comment]
好吧看来只有接触了才晓得对方是个什么样的人，你的东西我会完全删除，我自己从头再写一个

**Comment by CrymanChen** [comment]
You have been blocked. Goodbye~
