### ISSUE TITLE
Request?

### ISSUE THREAD

**Issue by KaIZeR99-code** [CrymanChen/WKS-KEYS#2]
Can I request script from other L3 sites?

**Comment by CrymanChen** [comment]
Yes you can.
My policy is that, you should try yourself first. **However, if you don't want to struggle with these and decide to turn to me, it's not free since it will cost me some time to do it.** Email is always available but please always be patient.

**Comment by KaIZeR99-code** [comment]
I'm not good enough to do it myself, that's why I'm asking you. Btw, my request is for 18+ site which is GIGA. You can search akiba-web on google. If you do agree, you can state the price and I'll update you if I can pay or not.

**Comment by CrymanChen** [comment]
No to the NSFW contents.
