### ISSUE TITLE
Protobuf error

### ISSUE THREAD

**Issue by peacetwo** [CrymanChen/WKS-KEYS#3]
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
 

How can I resolve this issue, I tried to downgrade the protobuf but then pywidevine woud not work with the downgraded version

**Comment by CrymanChen** [comment]
Try `pip install protobuf==3.19.5`  
One thing is that you shouldn't downgrade protobuf too much.
