### ISSUE TITLE
no client ID blob available for this device - what did I wrong ?

### ISSUE THREAD

**Issue by ds2k5** [CrymanChen/WKS-KEYS#5]
Hi,
what did I wrong ?

1. login to portal
2. select video an play
3. Open Web Dev. Tools in Firefox
4. search MPD  / Link to: mpd file
5. download the mpd file (wget)
6. git clone https://github.com/CrymanChen/WKS-KEYS
7. right click to MPD in Web Dev Tools  get VALUE -> get as CURL
8. paste at https://curlconverter.com/
9. save the headers block in headers.py
10. python3 l3mubi.py, add the VALUE of the LINE: cenc:default_KID in "Key ID:"
11. add VALUE of <cenc:pssh in "dt-custom-data:"

got error:

no client ID blob available for this device

**Comment by CrymanChen** [comment]
Attaching a screenshot would be preferable.  
Back to your statement, you said (in No. 7) you copied the cURL of the "mpd", however, you should find the license request which is a POST request, and copy the cURL (bash) of that, rather than the mpd GET request.  

P.S. One more thing, `headers.py` is not necessary when using l3mubi.py, I made some improvements last night just trying to optimize this.

**Comment by ds2k5** [comment]
>Attaching a screenshot would be preferable.

![Screenshot_2023-11-12_13-46-29](https://github.com/CrymanChen/WKS-KEYS/assets/11292286/311cd1ae-1946-4538-946b-55abb0bc09bb)

>Back to your statement, you said (in No. 7) you copied the cURL of the "mpd", however, you should find the license request >which is a POST request, and copy the cURL (bash) of that, rather than the mpd GET request.

did you mean this for example ?

![Screenshot_2023-11-12_13-49-39](https://github.com/CrymanChen/WKS-KEYS/assets/11292286/7cf8b8c4-f9a1-4d97-ad67-c8226aa8dcb2)

**Comment by CrymanChen** [comment]
First of all, please check my screenshot in the README.md, **the param you input is incorrect**.  
Second, please have a look at the name, the platform it designed for is written in the filename. Based on the domain in your second screenshot, **I doubt it's the same platform as it is in my script**.  

P.S. I used a Windows CMD function 'cls' to force clearing the window upon its start, but it maybe not working in your OS.
