### ISSUE TITLE
not working anymore with accounts with nv-authorizations?

### ISSUE THREAD

**Issue by marioeivissa** [CrymanChen/WKS-KEYS#7]
anybody have the same problems with accounts like orang tv and vodaftv? i tried differents ways to get the keys, but without results i tried with protobuf 3.19.5, 3.20.1, 3.20.2, 3.20.3, 4.xx.x etc but with acconts that are using the license web nagra.com not working, maybe i have to configurated different way my l3.py but i used differents ways also, i put just the headers without anymore, i used headers with data and request.post, and no results, i dont know why? i used with l3.py with data=data and json=data inserting a token, and uuid than i saw in a json file, and inserting more segments i say but not result at all, and i used l3.py with widevineBody, and  rawLicenseRequestBase64 because i think nagra.com is different to widevine license, but any results, i tried to use a drmlicense also touching the l3.py inside putting json=data and bla bla bla but not results at all i know a friend with vomistar account that happen de same like me, is using this account nv-authorizations also and he cant make work wks.keys, any advice please?

**Comment by CrymanChen** [comment]
Please write me an email including your account and password and the site you are requesting.

**Comment by marioeivissa** [comment]
> Please write me an email including your account and password and the site you are requesting.

ok i did, keep it in right place please, thanks

**Comment by marioeivissa** [comment]
i did already, thanks
________________________________
De: Cryman ***@***.***>
Enviado: domingo, 19 de noviembre de 2023 8:30
Para: CrymanChen/WKS-KEYS ***@***.***>
Cc: marioeivissa ***@***.***>; Author ***@***.***>
Asunto: Re: [CrymanChen/WKS-KEYS] not working anymore with accounts with nv-authorizations? (Issue #7)


Please write me an email including your account and password and the site you are requesting.

**Comment by CrymanChen** [comment]
Issue closed due to problems not related to scripts.

**Comment by marioeivissa** [comment]
my friend how did you get the keys if ours cdm are not working, thanks
________________________________
De: Cryman ***@***.***>
Enviado: domingo, 19 de noviembre de 2023 10:18
Para: CrymanChen/WKS-KEYS ***@***.***>
Cc: marioeivissa ***@***.***>; Author ***@***.***>
Asunto: Re: [CrymanChen/WKS-KEYS] not working anymore with accounts with nv-authorizations? (Issue #7)


Closed #7<https://github.com/CrymanChen/WKS-KEYS/issues/7> as completed.
