### ISSUE TITLE
dose it support json widevine ?

### ISSUE THREAD

**Issue by imrsaleh** [CrymanChen/WKS-KEYS#8]
www.vrt.be
www.starzplay.com
these sites has the same type of DRM
i already have paid access to these site and ready to provide any information you want

**Comment by CrymanChen** [comment]
Yes.

**Comment by imrsaleh** [comment]
![‏‏لقطة الشاشة (3)](https://github.com/CrymanChen/WKS-KEYS/assets/119083621/41e3f9e8-0528-45dc-8db8-e485c6d8b2a5)

i dont know whats wrong

**Comment by CrymanChen** [comment]
1. You have edited the l3.py script, so I don't know what you have input.  
2. Based on the content of 'widevine_license', it means HTTP 403.  
3. (Assumption) You may be missing 3 important parameters: **token**, **drm_info**, **kid**, and you should convert your original license request into an array. Further details are inappropriate to be discussed here publicly.  
This is what I met some time earlier. You should edit your script.  
![image](https://github.com/CrymanChen/WKS-KEYS/assets/106590233/5fcf8569-3616-4bad-8240-a2fc2035f506)

**Comment by imrsaleh** [comment]
Thank you for your response. I was able to send the request correctly, but there is a small problem, perhaps in how to write the print keys. For example, see the image.
![key](https://github.com/CrymanChen/WKS-KEYS/assets/119083621/30ac1fd6-6b00-47b0-864d-c1b55ba278d4)

i use this on my script:
`return {key.kid.hex: key.key.hex() for key in keys}`
`for key_id, key_value in keys.items():
    print(f'--key {key_id}:{key_value}')`

**Comment by CrymanChen** [comment]
I don't know lol, maybe it's the session ID.  
As for the key output, why not just:  
```
for key in keys: 
    print('--key' + key)
```
I assume that you are using the pywidevine style.

**Comment by imrsaleh** [comment]
`for key in keys: 
    print('--key' + key)`

i got these :(
`--key00000000000000000000000000000000
--keya00db63003f2481dc8e8240865bbc988`

**Comment by imrsaleh** [comment]
this code fix the problem, you can close

> for key in cdm.get_keys(session_id):
    if key.type != 'SIGNING':
        print(f"\n--key {key.kid.hex}:{key.key.hex()}")
